#!/bin/bash

command -v secret-tool >/dev/null && \
    secret-tool lookup host "$(hostname)" 2>/dev/null || \
    (
    echo -n '
Please add your sudo password to your login keyring with:

secret-tool store --label="Login" host $(hostname)

(password) ' >&2
    stty -echo
    head -n 1
    stty echo
    )
