#!/bin/bash
##DESC## Creates a simple video from an audio file and a still image.

if [ $# -lt 3 ]; then
    echo "Usage: audio-img-video <audio file> <image> <output file>" >&2
    exit 1
fi

audio="$1"
img="$2"
video="$3"

ffmpeg -loop 1 -i "$img" -i "$audio" -c:v libx264 -tune stillimage -c:a aac -b:a 192k -pix_fmt yuv420p -shortest "$video"
