#!/bin/bash
cd ~/.config/conky/ || exit 1

sleep 1

that_weird_spectrumyzer_stuff() {
    echo "Well, I guess we like spectrumyzer, so let's deal with that first... killing old spectrumyzer... "
    killall spectrumyzer 2>/dev/null
    echo "... and time to start it back up... "
    (spectrumyzer &)
    echo "okiedokie, all gucci :D"
    echo
}

contains() {
    toCheck="$1"
    shift

    for item in "$@"; do 
        if [[ "$item" = "$toCheck" ]]; then
            return 0
        fi
    done

    return 1
}

# that_weird_spectrumyzer_stuff

echo "Killing all conky instances... "
killall conky 2>/dev/null

DISABLED_MODULES=( $(cat disabled-modules) )
echo "Disabled modules: ${DISABLED_MODULES[*]}"

for module in ./*.conf; do
    modname="$(basename "$module" ".conky")"

    if contains "$modname" "${DISABLED_MODULES[@]}"; then
        echo "Skipping disabled module '$modname'"
    else
        echo -n "Starting module '$modname'... "
        (conky -d -c "$module" &>/dev/null || ( echo "The module '$modname' failed to start" 1>&2; exit 1 ) &)
        echo "done"
    fi
done

