#!/bin/bash
##DESC## Adds my template .gitignore file to a project. It puts the file into ~/GitHub/$1.

TEMPLATE_FILE="$HOME/GitHub/.templates/gitignore"

if [ ! -f "$TEMPLATE_FILE" ]; then
    echo "gi is set up incorrectly! There should be a file named 'gitignore' in '$(dirname "$TEMPLATE_FILE")', but none was found. Please correct this and then try again." >&1
    exit 1
fi

if [ $# -lt 1 ]; then
    echo "Usage: gi <folder>" >&1
    exit 1
fi

if [ ! -d ~/GitHub/"$1" ]; then
    echo "'$1' is not a project." >&1
    exit 1
fi

cp "$TEMPLATE_FILE" ~/GitHub/"$1"/.gitignore
echo "Copied template .gitignore to '$1'"
