#!/bin/bash

fail() {
    echo "$*" >&2
    exit 1
}

prop() {
    git config -l | grep -E "^$1" | head -n1 | cut -d= -f2-
}

if ! git status &>/dev/null; then
    fail "You are not in a git repository!"
fi

REMOTE="$(git for-each-ref --format='%(upstream:short)' $(git symbolic-ref -q HEAD))"

if [ ! "$REMOTE" ]; then
    fail "No remote could be found!"
fi

REMOTE_NAME="$(cut -d / -f 1 <<< "$REMOTE")"
REMOTE_BRANCH="$(cut -d / -f 2- <<< "$REMOTE")"

REMOTE_URL="$(git remote get-url "$REMOTE_NAME")"

if [ ! "$REMOTE_URL" ]; then
    fail "No URL found for remote '$REMOTE_NAME'"
fi

echo -n "$REMOTE_URL" | sed -e 's;\.git$;;g' -e 's;^git@\(.\+\):\(.\+\)/\(.\+\)$;https://\1/\2/\3;g'

if [ ! -z "$REMOTE_BRANCH" ] && [ "$REMOTE_BRANCH" != "master" ]; then
    if [ "$1" = "-p" ]; then
        echo -n "/pull/$REMOTE_BRANCH"
    else
        echo -n "/tree/$REMOTE_BRANCH"
    fi
fi
