#!/bin/bash

fail() {
    echo "$*" >&1
    exit 1
}

prop() {
    git config -l | grep -E "^$1" | head -n1 | cut -d= -f2-
}

if [ ! -d .git ]; then
    fail "You are not in a git repository!"
fi

REMOTE_NAME="$(git for-each-ref --format='%(upstream:short)' $(git symbolic-ref -q HEAD) | cut -d / -f 1)"

if [ ! "$REMOTE_NAME" ]; then
    fail "No remote could be found!"
fi

REMOTE_URL="$(git remote get-url "$REMOTE_NAME")"

if [ ! "$REMOTE_URL" ]; then
    fail "No URL found for remote '$REMOTE_NAME'"
fi

echo "$REMOTE_URL" | sed 's;^git@github.com:\(.\+\)/\(.\+\)$;https://github.com/\1/\2;g'