#!/bin/bash

if ! command -v playerctl >/dev/null; then
    exit 1
fi

if playerctl -l 2>&1 | grep -q 'No players were found'; then
    exit 1
fi

status="$(playerctl status)"

symbol=""

if [[ "$status" = "Playing" ]]; then
    symbol=$'\ue602'
elif [[ "$status" = "Paused" ]]; then
    symbol=$'\uf8e3'
else
    exit 0
fi

printf '%s %s - %s' "$symbol" "$(playerctl metadata artist)" "$(playerctl metadata title)"
