#!/bin/bash
##DESC## Opens a file using the DE/OS-specific system.
# vi:syntax=bash

os="$(uname)"

if command -v wslview >/dev/null; then
    wslview "$*" &>/dev/null
elif [ $os = "Linux" ]; then
    xdg-open "$*" &>/dev/null
elif [ $os = "Darwin" ]; then
    /usr/bin/open "$*"
else
    echo "I don't know how to handle the operating system '$os'" >&2
    exit 1
fi

if [[ $? != 0 ]]; then
    echo "Failed to open '$*'"
fi
