#!/bin/bash
##DESC## Creates a new Bukkit plugin via my Maven archetype.

# Fail on error
set -e

COLOR_MAIN="$(tput setaf 2)"
COLOR_SECONDARY=$(tput setaf 4)
COLOR_RESET="$(tput sgr0)"

err() {
    echo -e "$item" >&2
    exit 1
}

prompt_confirm() {
    while true; do
        read -r -p "(Y/n) " response
        case $response in
            [yY][eE][sS]|[yY])
                return 0
                ;;
            [nN][oO]|[nN])
                return 1
                ;;
            *)
                echo "Invalid input: $response"
                ;;
        esac
    done
}

usage() {
    err "
Usage: proj <name> [author] [group] [version] [folder]
            name        The name of this project
            author      The author of the project (defaults to 'Rayzr')
            group       The group (defaults to 'me.rayzr522')
            version     The version (defaults to '1.0.0')
            folder      Where to put this (defaults to $HOME/GitHub/)
"
}

if [ $# -lt 1 ]; then
    usage
fi

NAME="$1"
AUTHOR="${2:-Rayzr}"
DIR="${3:-$HOME/GitHub/}"
GROUP="${4:-me.rayzr522}"
VERSION="${5:-1.0.0}"

if [ -f "$DIR" ]; then
    err "There's already a file at $COLOR_MAIN$DIR"
fi

if [ ! -d "$DIR" ]; then
    echo "Making a folder at $COLOR_MAIN$DIR"
    mkdir "$DIR"
fi

echo "Creating $COLOR_MAIN$NAME$COLOR_RESET v$COLOR_MAIN$VERSION$COLOR_RESET for group $COLOR_MAIN$GROUP$COLOR_RESET..."

cd "$DIR" || {
    err "Failed to cd into $DIR"
}

LOWER="$(echo "$NAME" | tr '[:upper:]' '[:lower:]')"

FOLDER="$LOWER"

if [ -d "$NAME" ] || [ -d "$LOWER" ]; then
    if [ -d "$NAME" ]; then
        FOLDER="$NAME"
    fi

    echo "There's already a project with that name."
    echo "Do you want to$COLOR_SECONDARY overwrite$COLOR_RESET it?"

    prompt_confirm && {
        rm -rf "$FOLDER"
    } || exit 1
fi

echo

echo "Please enter a$COLOR_SECONDARY description$COLOR_RESET for the plugin (or leave empty to use the default description)"
read -r -p "$COLOR_SECONDARY>$COLOR_RESET " DESCRIPTION

if [ -z "$DESCRIPTION" ]; then
    DESCRIPTION="A Bukkit plugin"
fi

echo

echo -n "Generating project with$COLOR_SECONDARY Maven$COLOR_RESET..."

mvn archetype:generate \
    --quiet \
    -DinteractiveMode=false \
    -DarchetypeGroupId=me.rayzr522 \
    -DarchetypeArtifactId=mvn-archetype-bukkit-base-plugin \
    -DarchetypeVersion=1.1.1 \
    -DgroupId="$GROUP" \
    -DartifactId="$LOWER" \
    -Dversion="$VERSION" \
    -Dname="$NAME" \
    -Dauthor="$AUTHOR" \
    -Ddescription="$DESCRIPTION"

mvnStatus=$?

if [ $mvnStatus != 0 ]; then
    echo
    err "Project creation failed."
fi

echo "$COLOR_SECONDARY done$COLOR_RESET."

FOLDER="$LOWER"
if [ -d "$FOLDER" ]; then
    mv "$LOWER" "$NAME" 2> /dev/null
    FOLDER=$NAME
fi

echo "Would you like to set up a local git repository for this plugin?"
prompt_confirm || exit 0

cd "$FOLDER" || exit 1

git init
echo -e "# $NAME\n\n> $DESCRIPTION\n\n*Note: This README is a pre-generated stub.*\n\n## Join Me\n\n[![Discord Badge](https://github.com/Rayzr522/ProjectResources/raw/master/RayzrDev/badge-small.png)](https://rayzr.dev/join)" >> README.md

git add .
git commit -m "Project '$NAME' generated" \
    -m "Generated using mvn-archetype-bukkit-base-plugin and custom CLI project generator tool by Rayzr" 1>/dev/null || exit 1

echo "Would like to create a GitHub repo for this plugin?"
prompt_confirm || exit 0

github-repo "$NAME" "$DESCRIPTION" && {
    echo
    echo "The repository is now avilable at https://github.com/$(git config --get user.name)/$NAME.git"
    echo
} || exit 1
