#!/bin/bash
set -e

UPDATEDIR=/tmp/minecraft-launcher-update

[[ -d "$UPDATEDIR" ]] && rm -rf "$UPDATEDIR"
mkdir -p "$UPDATEDIR"
cd "$UPDATEDIR"

wget https://launcher.mojang.com/mc-staging/download/Minecraft_staging.tar.gz
tar xvf ./Minecraft_staging.tar.gz

sudo rm -rf /opt/minecraft-launcher
ls
sudo mv ./minecraft-launcher-* /opt/minecraft-launcher

if [[ -x /opt/minecraft-launcher/minecraft-launcher.sh ]] && [[ ! -x /opt/minecraft-launcher/minecraft-launcher ]]; then
    sudo ln -s /opt/minecraft-launcher/minecraft-launcher.sh /opt/minecraft-launcher/minecraft-launcher
fi

rm -rf "$UPDATEDIR"
