#!/bin/bash

export SUDO_ASKPASS="$HOME/.bin/askpass-secret-tool"

if ! command -v openvpn >/dev/null; then
    echo "openvpn not installed" 1>&2
    exit 1
fi

if [[ ! -f ~/.config/ovpn/client.ovpn ]]; then
    echo "openvpn config not found at ~/.config/ovpn/client.ovpn" 1>&2
    exit 1
fi

action_usage() {
    echo "Usage: $(basename "$0") [-k|-s]" 1>&2
    exit 1
}

action_start() {
    sudo -A openvpn --config ~/.config/ovpn/client.ovpn --auth-user-pass --daemon
}

action_kill() {
    sudo -A killall openvpn 2>/dev/null
    if [[ $? = 0 ]]; then
        echo "Killed OpenVPN daemon"
    else
        echo "Could not kill OpenVPN daemon -- it might not be running" 1>&2
        exit 1
    fi
}

action_status() {
    if pgrep openvpn >/dev/null; then
        echo "OpenVPN daemon is currently: $(tput setaf 2)running$(tput sgr0)"
    else
        echo "OpenVPN daemon is currently: $(tput setaf 1)not running$(tput sgr0)"
    fi
}

if [[ -z "$1" ]]; then
    action_start
elif [[ "$1" = "-k" ]]; then
    action_kill
elif [[ "$1" = "-s" ]]; then
    action_status
else
    action_usage
fi
