#!/bin/bash

if ! command -v openvpn >/dev/null; then
    echo "openvpn not installed" 1>&2
    exit 1
fi

if [[ ! -f ~/.config/ovpn/client.ovpn ]]; then
    echo "openvpn config not found at ~/.config/ovpn/client.ovpn" 1>&2
    exit 1
fi

if [[ -z "$1" ]]; then
    sudo openvpn --config ~/.config/ovpn/client.ovpn --auth-user-pass --daemon
elif [[ "$1" = "-k" ]]; then
    sudo killall openvpn 2>/dev/null
    if [[ $? = 0 ]]; then
        echo "Killed OpenVPN daemon"
    else
        echo "Could not kill OpenVPN daemon -- it might not be running" 1>&2
        exit 1
    fi
else
    echo "Usage: $(basename "$0") [-k]" 1>&2
    exit 1
fi
