#!/bin/bash

findFactors() {
    originalNum="$1"
    num="$originalNum"

    declare -a out

    if [[ $num -lt 4 ]]; then
        out+=($num)
    else
        for i in $(seq 2 "$num"); do
            while [[ $((num % i)) = 0 ]]; do
                out+=($i)
                num=$((num / i))
            done

            if [[ $num = 1 ]]; then
                break
            fi
        done
        if [[ $num != 1 ]]; then
            out+=($num)
        fi
    fi

    echo "${out[*]}" | tr ' ' 'x'
}

if [[ $# -lt 1 ]]; then
    while read -r num; do findFactors "$num"; done
else
    findFactors "$1"
fi
