#!/bin/bash

set -x

while [[ ! "$DISPLAY" ]]; do
    echo "Waiting for display to start conky..."
    sleep 1
done

killall conky 2>/dev/null
[ -x ~/.config/conky/now-clocking/start.sh ] && ~/.config/conky/now-clocking/start.sh
