#!/bin/bash

export SUDO_ASKPASS="$HOME/.bin/askpass-secret-tool"

echo -n "0000:02:00.0" | sudo -A tee /sys/bus/pci/drivers/xhci_hcd/unbind
sleep 2
echo -n "0000:02:00.0" | sudo -A tee /sys/bus/pci/drivers/xhci_hcd/bind

