#!/usr/bin/env node

const primes = limit => {
    const out = [];
    for (let i = 1; i <= limit; i++) {
        let isPrime = true;
        for (let n = 2; n < i; n++) {
            if (i % n == 0) {
                isPrime = false;
                break;
            }
        }
        if (isPrime) {
            out.push(i);
        }
    }
    return out;
};

const main = args => {
    if (isNaN(args[0])) {
        console.error('Usage: node-primes <limit>');
        process.exit(1);
    }

    const limit = parseInt(args[0]);
    console.log(primes(limit).join(', '));
};

main(process.argv.slice(2));
