#!/bin/bash

if ! command -v playerctl >/dev/null; then
    exit 1
fi

if playerctl -l 2>&1 | grep -q 'No players were found'; then
    exit 1
fi

playerctl_player="$(playerctl -l | grep -v plasma-browser-integration | head -n1)"

playerctl_exec() {
    playerctl -p "$playerctl_player" "$@"
}

playerctl_meta() {
    playerctl_exec metadata "$@"
}

status="$(playerctl_exec status)"

symbol=""

if [[ "$status" = "Playing" ]]; then
    symbol=$'\uf04b'
elif [[ "$status" = "Paused" ]]; then
    symbol=$'\uf04c'
else
    exit 0
fi

printf '%s %s - %s' "$symbol" "$(playerctl_meta artist)" "$(playerctl_meta title)"
