#!/usr/bin/env python

from sys import argv


def factors(num):
    """
    Finds all the factors of the given number
    """

    if num < 4:
        return [num]

    out = []

    for i in range(2, num):
        while num % i == 0:
            num /= i
            out.append(i)
        if num == 1:
            break

    if num != 1:
        out.append(num)

    return out


if len(argv) <= 1:
    print("Usage: python-factors <number>")
    exit(1)

num = int(argv[1])
out = map(str, factors(num))

print("x".join(out))
