#!/usr/bin/env python
from sys import argv

def primes(limit):
    """Gets all prime numbers up to a given limit"""

    out = []
    for i in range(1, limit + 1):
        prime = True
        for j in range(2, i):
            if i % j == 0:
                prime = False
                break

        if prime:
            out.append(i)

    return out

if len(argv) < 1:
    print("Usage: python-primes <limit>")
    exit(1)

limit=int(argv[1])
results=map(str, primes(limit))

print(", ".join(results))
